import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./admin/components/Sidebar";
import TopNav from "./admin/components/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
      >
       <div className="flex h-screen ">
        <Sidebar/>
        <div className="flex-1 flex flex-col overflow-hidden">
          <TopNav/>
          <div className="flex-1 overflow-y-auto p-6 ">
            {children}
          </div>
        </div>
      </div>
      </body>
    </html>
  );
}
